# Kubernetes Deployment for Nginx
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-helm-chart.fullname" . }}
  labels:
    {{- include "nginx-helm-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx-helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx-helm-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            {{- if .Values.https.enabled }}
            - name: https
              containerPort: 443
              protocol: TCP
            {{- end }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            {{- if .Values.https.enabled }}
            - name: ssl-certs
              mountPath: /etc/nginx/ssl
            {{- end }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "nginx-helm-chart.fullname" . }}-config
        {{- if .Values.https.enabled }}
        - name: ssl-certs
          secret:
            secretName: {{ include "nginx-helm-chart.fullname" . }}-ssl
        {{- end }}